---
apiVersion: hypershift.openshift.io/v1alpha1
kind: HostedCluster
metadata:
  name: my-demo
  namespace: clusters
spec:
  release:                                                          # USER_DEFINED_START
    image: quay.io/openshift-release-dev/ocp-release:4.9.5-x86_64
  services:
  - service: APIServer
    servicePublishingStrategy:
      type: LoadBalancer
  - service: OAuthServer
    servicePublishingStrategy:
      type: Route
  - service: OIDC
    servicePublishingStrategy:
      type: S3
  - service: Konnectivity
    servicePublishingStrategy:
      type: Route
  - service: Ignition
    servicePublishingStrategy:
      type: Route                                                 # USER_DEFINED_END
  dns:                                                            # PASTE_FROM_PROVIDERPLATFORM_START
    baseDomain: my-domain.com
    privateZoneID: ...
    publicZoneID: ...
  infraID: my-demo-XXXXX
  issuerURL: https://BUCKET.s3.us-east-1.amazonaws.com/my-demo-XXXXX
  networking:
    machineCIDR: 10.0.0.0/16
    networkType: OpenShiftSDN
    podCIDR: 10.132.0.0/14        # USER_DEFINED
    serviceCIDR: 172.31.0.0/16    # USER_DEFINED
  platform:
    aws:
      cloudProviderConfig:
        subnet:
          id: subnet-...
        vpc: vpc-...
        zone: us-east-1a
      endpointAccess: Public
      kubeCloudControllerCreds:
        name: my-demo-cloud-ctrl-creds
      nodePoolManagementCreds:
        name: my-demo-node-mgmt-creds
      region: us-east-1
      roles:
      - arn: arn:aws:iam::.....
        name: cloud-credentials
        namespace: openshift-ingress-operator
      - arn: arn:aws:iam::.....
        name: installer-cloud-credentials
        namespace: openshift-image-registry
      - arn: arn:aws:iam::.....
        name: ebs-cloud-credentials
        namespace: openshift-cluster-csi-drivers
    type: AWS
  providerPlatformCreds:
    name: aws
  pullSecret:
    name: pull-secret
  securityGroups:
  - id: sg-...
  sshKey: {}                                                      # PASTE_FROM_PROVIDERPLATFORM_END
---
apiVersion: hypershift.openshift.io/v1alpha1
kind: NodePool
metadata:
  name: my-demo
  namespace: clusters
spec:
  clusterName: my-demo
  nodeCount: 2
  nodePoolManagement:
    autoRepair: false
    replace:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      strategy: RollingUpdate
    upgradeType: Replace
  platform:
    aws:
      instanceProfile: my-demo-XXXXX-worker  # COPY_FROM_ABOVE
      instanceType: t3.2xlarge
      rootVolume:
        size: 35
        type: gp2
      securityGroups:
      - id: sg-...      # COPY_FROM_ABOVE
      subnet:
        id: subnet-...  # COPY_FROM_ABOVE
    type: AWS
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.9.5-x86_64