---
apiVersion: hypershift.openshift.io/v1alpha1
kind: HostedCluster
metadata:
  name: my-demo
  namespace: clusters
spec:
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.9.5-x86_64
  services:
  - service: APIServer
    servicePublishingStrategy:
      type: LoadBalancer
  - service: OAuthServer
    servicePublishingStrategy:
      type: Route
  - service: OIDC
    servicePublishingStrategy:
      type: S3
  - service: Konnectivity
    servicePublishingStrategy:
      type: Route
  - service: Ignition
    servicePublishingStrategy:
      type: Route
  networking:
    podCIDR: 10.132.0.0/14
    serviceCIDR: 172.31.0.0/16
  pullSecret:
    name: pull-secret
  platform:
    type: AWS
  sshKey: {}
  providerPlatformRef:
    name: my-demo
