---
apiVersion: hypershift.openshift.io/v1alpha1
kind: NodePool
metadata:
  name: my-demo
  namespace: clusters
spec:
  clusterName: my-demo
  nodeCount: 2
  management:
    autoRepair: false
    replace:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      strategy: RollingUpdate
    upgradeType: Replace
  platform:
    aws:
      instanceType: t3.2xlarge
      rootVolume:
        size: 35
        type: gp2
    type: AWS
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.9.5-x86_64
