site_name: HyperShift
theme:
  name: material
  features:
  - navigation.tabs
  - toc.integrate
  - content.code.annotate
plugins:
- search
- mermaid2
docs_dir: content
repo_url: https://github.com/openshift/hypershift
repo_name: openshift/hypershift
markdown_extensions:
- toc:
    toc_depth: "2-2"
- attr_list:
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.superfences:
    # make exceptions to highlighting of code:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:mermaid2.fence_mermaid
- pymdownx.snippets
- admonition
- pymdownx.details
